### ISSUE TITLE
Unexpected fields in JSON Schema

### ISSUE THREAD

**Issue by smoya** [GreenRover/proto-schema-parser#1]
I noticed the resulting JSON Schema contains unexpected fields, such as `repeated` and `optional` (there are more), which are clearly [Protobuf field rules](https://protobuf.dev/programming-guides/proto3/#specifying-field-rules).

See https://github.com/GreenRover/proto-schema-parser/blob/master/test/comments.proto.result.json#L43-L44

I expect those should not be included in the produced JSON Schema.

**Comment by GreenRover** [comment]
was fixed, no more funny extra fields. That are not start with "x-"
